#lang s-exp "../../../private/mapping-lang.rkt"


(number? 数?)
(complex? 复数?)
(real? 实数?)
(rational? 有理数?)
(integer? 整数?)
(exact-integer? 精确整数?) ;;??
(exact-nonnegative-integer? 精确非负整数?)
(exact-positive-integer? 精确正整数?)
(inexact-real? 非精确实数?)
;; (fixnum? )
(flonum? 浮点数?)
(double-flonum? 双浮点数?)
(single-flonum? 单浮点数?)
(single-flonum-available? 支持单浮点数?)
(zero? 零?)
(positive? 正数?)
(negative? 负数?)
(even? 偶数?)
(odd? 奇数?)
(exact? 精确数?)
(inexact? 非精确数?)
(inexact->exact 非精确->精确数)
(exact->inexact 精确->非精确数)
(real->single-flonum 实->单浮点数)
(real->double-flonum 实->双浮点数)
